# Generated by Django 4.1.1 on 2023-09-18 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('Price', models.CharField(max_length=30)),
                ('Quantity', models.CharField(max_length=30)),
                ('Category', models.CharField(max_length=30)),
            ],
        ),
    ]
